LOCALHOST### 
GET http://localhost:8080/contacts 
### 
GET http://localhost:8080/contacts/6444b20e9077742ed52f7c7b ### GET http://localhost:8080/contacts/6444b2d69077742ed52f7c7c ### GET http://localhost:8080/contacts/6444b2d69077742ed52f7c7d ### GET http://localhost:8080/contacts/6444b2d69077742ed52f7c7e

// PRODUCTION Deploy ### GET https://swain341-test.onrender.com/contacts ### GET https://swain341-test.onrender.com/contacts/6444b2d69077742ed52f7c7b ### GET https://swain341-test.onrender.com/contacts/6444b2d69077742ed52f7c7c ### GET https://swain341-test.onrender.com/contacts/6444b2d69077742ed52f7c7d ### GET https://swain341-test.onrender.com/contacts/6444b2d69077742ed52f7c7e